### ISSUE TITLE
[Source Code] keras layers에서 merge를 import할 때 에러

### ISSUE THREAD

**Issue by syl0921** [Zerohertz/Korean-QnA-model-based-on-KorQuAD-1.0#10]
![image](https://user-images.githubusercontent.com/109730534/202111556-1dd339a5-b702-40a6-84e2-68ff9f279637.png)

위에 나온 것 처럼 dot과 concatenate만 import할 때는 문제가 없는데, merge를 import하려면 에러가 뜨네요. 찾아보니까 gpu얘기도 나오고, 버전(2 이상) 얘기도 나오는데 혹시 문제없이 import하신 분 있나요?

**Comment by leeyubin10** [comment]
from tensorflow.python.keras.layers import merge, dot, concatenate
위에 코드로 변경해서 실행해주시면 될 것 같아요!

**Comment by syl0921** [comment]
그렇게 하니 되네요 :)
