### ISSUE TITLE
[Source Code] error 발생

### ISSUE THREAD

**Issue by jwshin0908** [Zerohertz/Korean-QnA-model-based-on-KorQuAD-1.0#8]
tensorflow 다운그레이드 이후 keras 쪽에서 계속 error가 발생하는데 하나를 넘기면 또 하나에서 생기고, 모델링 과정에서도 계속해서 이런 현상이 생길 것 같은 불안한 느낌이 드는데.. 다들 초반 module import 부분 어떻게 하셨나요..코드 올려주시면 감사하겠습니다.

<img width="681" alt="image" src="https://user-images.githubusercontent.com/59306720/201935510-a179be67-be3e-4136-95f4-94bb4ba63d74.png">

**Comment by eunbinni** [comment]
저도 1.15버전으로 해봤는데 같은 오류나네요 ㅠㅠ 제가 2버전으로 해봤는데 모델링 전까지는 실행이 문제 없이 되는데, 모델 실행 부터는 버전 충돌로 안되네요 ,, 모델부분을 저희가 수정해보는건 어떤가요??? 

<img width="1221" alt="스크린샷 2022-11-15 오후 11 19 56" src="https://user-images.githubusercontent.com/97430653/201943355-a9a5d4ff-6863-4264-ad0b-7f50a5ec3bfa.png">

**Comment by Zerohertz** [comment]
@eunbinni 

~~~python
import tf.compat.v1 as tf
~~~

임포트를 상단 코드로 바꿔서 해보실래요??

**Comment by leeyubin10** [comment]
tensorflow를 다운그레이드 했을 때 아래와 같이 tensorflow.keras 이런식으로 변경해서 코드 작성하니까 실행 되긴 했습니다.!
![image](https://user-images.githubusercontent.com/68275474/201954337-1f58fb7e-2550-496e-b051-080f91646349.png)

**Comment by leeyubin10** [comment]
!pip install keras-rectified-adam

뒤에 부분 코드 실행할 때 from keras_radam import RAdam <- 이렇게 실행하면 오류가 생기는데,  위에 코드로 변경해서 실행하면 해결됩니다:)
