### ISSUE TITLE
[Source code] RAM 다운

### ISSUE THREAD

**Issue by eunbinni** [Zerohertz/Korean-QnA-model-based-on-KorQuAD-1.0#9]
혹시 코드 모두실행했을때 전부 다 돌아간 분 있나요 ...? 저는 코랩에서 했고 RAM다운되어서,,

**Comment by jwshin0908** [comment]
저도 여기서 RAM이 끊겼어요.. parameter가 1억 7천만 개라 감당못하는 것 같아요

<img width="525" alt="image" src="https://user-images.githubusercontent.com/59306720/202080582-70e4e3a4-8c90-40bd-9e06-c66f01701e91.png">

**Comment by syl0921** [comment]
아뇨.. 저도 아래 코드 돌릴 때 램다운 됐어요.

![image](https://user-images.githubusercontent.com/109730534/202110313-092c2ed4-1876-4030-aaef-2cdc0cbb1e13.png)

**Comment by leeyubin10** [comment]
batch_size를 줄이면 RAM 문제가 발생하지 않을 수 있다고 해서 batch_size를 줄여서 실행해보고 있는데, 이렇게 하면 실행 시간이 길어서 코랩의 GPU 사용 시간에 제한이 될 것 같아요..

**Comment by Zerohertz** [comment]
Local 환경에서 실행하실 분은 아래 글을 통해서 가상 환경 구축하시면 돼요 !

> 파이썬 가상 환경 생성

~~~python
conda create -n QA python=3.7
~~~

> 가상 환경 활성화

~~~python
conda activate QA
~~~

> Jupyter Notebook 설치 및 실행

~~~python
conda install jupyter notebook
jupyter notebook
~~~



> TensorFlow 설치

~~~python
pip install tensorflow==1.15.2
~~~

> Pandas & NumPy 설치

~~~python
conda install -c anaconda pandas
conda install -c anaconda numpy
~~~

> tqdm 설치

~~~python
conda install -c conda-forge tqdm
~~~

> Keras 모듈 설치

~~~python
pip install keras==2.1.6
pip install keras-bert
pip install keras-rectified-adam
~~~

**Comment by Zerohertz** [comment]
![image](https://user-images.githubusercontent.com/42334717/202122218-44c4e667-6e6c-47e0-8b97-1f13cf98f629.png)

로컬을 통해서 실행해보니 학습이 가능한거 같긴해요
